### ISSUE TITLE
Could you release the pretrained weight "yolov3_vg.pth" Thanks !!

### ISSUE THREAD

**Issue by t22786959** [kingthreestones/RefCLIP#2]

**Comment by kingthreestones** [comment]
https://1drv.ms/u/s!Aka1OHHnFhDktDPUrZflYXkCXELa?e=SKJwXr

**Comment by t22786959** [comment]
First, Thanks a lot for reply!! 
Second, I want to know could you provide the instuctions to get below results. Or you havn't upload the related code. Thanks!
![image](https://github.com/kingthreestones/RefCLIP/assets/60769526/c63ed741-904b-48a2-b919-71047fa4789f)

**Comment by kingthreestones** [comment]
First, the pseudo-label is obtained by inference using RefCLIP (You can modify test.py to save box information),
 and then this pseudo-label is provided to the REC model for training according to their respective requirements

**Comment by t22786959** [comment]
Thanks a lot for the help!

**Comment by t22786959** [comment]
Sorry to bother you, I try to use the box information produced by RefCLIP to train the REC model, but I can't get the score like you provided. Could you provide more detailed instructions to get the RefCLIP_RealGIN, RefCLIP_SimREC, RefCLIP_TransVG scores. Thanks !!

**Comment by NimoXW** [comment]
I also have the same problem. Could you provide more detailed instructions to get the RefCLIP_RealGIN, RefCLIP_SimREC, and RefCLIP_TransVG scores? Thanks !!
